import XCTest
import SwiftData
import CryptoKit
@testable import Pasted

/// Tests for the ClipboardItem model (T009).
/// Verifies initialization, default values, ContentType encoding/decoding,
/// dataHash consistency, and byteSize calculation.
final class ClipboardItemTests: XCTestCase {

    // MARK: - Helpers

    /// Creates an in-memory ModelContainer for isolated test execution.
    private func makeContainer() throws -> ModelContainer {
        let schema = Schema([ClipboardItem.self])
        let config = ModelConfiguration(isStoredInMemoryOnly: true)
        return try ModelContainer(for: schema, configurations: [config])
    }

    // MARK: - Initialization

    func testInitWithAllParameters() throws {
        let id = UUID()
        let rawData = Data("Hello, World!".utf8)
        let capturedAt = Date(timeIntervalSince1970: 1_700_000_000)
        let thumbnail = Data([0xFF, 0xD8, 0xFF]) // Fake JPEG header

        let item = ClipboardItem(
            id: id,
            contentType: .text,
            rawData: rawData,
            plainTextContent: "Hello, World!",
            previewThumbnail: thumbnail,
            sourceAppBundleID: "com.apple.Safari",
            sourceAppName: "Safari",
            capturedAt: capturedAt,
            byteSize: 999
        )

        XCTAssertEqual(item.id, id)
        XCTAssertEqual(item.contentType, .text)
        XCTAssertEqual(item.rawData, rawData)
        XCTAssertEqual(item.plainTextContent, "Hello, World!")
        XCTAssertEqual(item.previewThumbnail, thumbnail)
        XCTAssertEqual(item.sourceAppBundleID, "com.apple.Safari")
        XCTAssertEqual(item.sourceAppName, "Safari")
        XCTAssertEqual(item.capturedAt, capturedAt)
        // When byteSize is explicitly provided, it should be used as-is
        XCTAssertEqual(item.byteSize, 999)
    }

    func testDefaultValues() throws {
        let rawData = Data("test".utf8)
        let beforeCreation = Date()

        let item = ClipboardItem(contentType: .text, rawData: rawData)

        let afterCreation = Date()

        // id should be auto-generated (non-nil UUID)
        XCTAssertNotNil(item.id)

        // capturedAt defaults to approximately now
        XCTAssertGreaterThanOrEqual(item.capturedAt, beforeCreation)
        XCTAssertLessThanOrEqual(item.capturedAt, afterCreation)

        // byteSize calculated from rawData when not provided
        XCTAssertEqual(item.byteSize, Int64(rawData.count))

        // Optional fields default to nil
        XCTAssertNil(item.plainTextContent)
        XCTAssertNil(item.previewThumbnail)
        XCTAssertNil(item.sourceAppBundleID)
        XCTAssertNil(item.sourceAppName)
    }

    func testAutoGeneratedIdsAreUnique() {
        let item1 = ClipboardItem(contentType: .text, rawData: Data("a".utf8))
        let item2 = ClipboardItem(contentType: .text, rawData: Data("b".utf8))

        XCTAssertNotEqual(item1.id, item2.id)
    }

    // MARK: - ContentType Codable Round-Trip

    func testContentTypeCodableRoundTrip() throws {
        let encoder = JSONEncoder()
        let decoder = JSONDecoder()

        for contentType in ContentType.allCases {
            let encoded = try encoder.encode(contentType)
            let decoded = try decoder.decode(ContentType.self, from: encoded)
            XCTAssertEqual(decoded, contentType, "Round-trip failed for \(contentType.rawValue)")
        }
    }

    func testContentTypeAllCasesExist() {
        // Verify all 5 expected cases are present
        let allCases = ContentType.allCases
        XCTAssertEqual(allCases.count, 5)
        XCTAssertTrue(allCases.contains(.text))
        XCTAssertTrue(allCases.contains(.richText))
        XCTAssertTrue(allCases.contains(.image))
        XCTAssertTrue(allCases.contains(.url))
        XCTAssertTrue(allCases.contains(.file))
    }

    func testContentTypeRawValues() {
        XCTAssertEqual(ContentType.text.rawValue, "text")
        XCTAssertEqual(ContentType.richText.rawValue, "richText")
        XCTAssertEqual(ContentType.image.rawValue, "image")
        XCTAssertEqual(ContentType.url.rawValue, "url")
        XCTAssertEqual(ContentType.file.rawValue, "file")
    }

    func testContentTypeDecodingFromRawString() throws {
        let decoder = JSONDecoder()

        for contentType in ContentType.allCases {
            let json = "\"\(contentType.rawValue)\"".data(using: .utf8)!
            let decoded = try decoder.decode(ContentType.self, from: json)
            XCTAssertEqual(decoded, contentType)
        }
    }

    // MARK: - dataHash

    func testDataHashConsistency_sameDataSameHash() {
        let data = Data("Hello, World!".utf8)
        let item1 = ClipboardItem(contentType: .text, rawData: data)
        let item2 = ClipboardItem(contentType: .text, rawData: data)

        XCTAssertEqual(item1.dataHash, item2.dataHash,
                       "Same rawData must produce the same dataHash")
    }

    func testDataHashConsistency_differentDataDifferentHash() {
        let item1 = ClipboardItem(contentType: .text, rawData: Data("Hello".utf8))
        let item2 = ClipboardItem(contentType: .text, rawData: Data("World".utf8))

        XCTAssertNotEqual(item1.dataHash, item2.dataHash,
                          "Different rawData must produce different dataHash values")
    }

    func testDataHashMatchesSHA256() {
        let data = Data("test data for hashing".utf8)
        let item = ClipboardItem(contentType: .text, rawData: data)

        // Independently compute SHA-256
        let digest = SHA256.hash(data: data)
        let expectedHash = digest.map { String(format: "%02x", $0) }.joined()

        XCTAssertEqual(item.dataHash, expectedHash)
    }

    func testDataHashIsHexEncoded() {
        let item = ClipboardItem(contentType: .text, rawData: Data("test".utf8))
        let hash = item.dataHash

        // SHA-256 produces 32 bytes = 64 hex characters
        XCTAssertEqual(hash.count, 64)

        // All characters should be valid hex
        let hexCharacterSet = CharacterSet(charactersIn: "0123456789abcdef")
        XCTAssertTrue(hash.unicodeScalars.allSatisfy { hexCharacterSet.contains($0) },
                      "dataHash should contain only lowercase hex characters")
    }

    func testDataHashDiffersForDifferentContentTypesSameData() {
        // dataHash is based solely on rawData, not contentType
        let data = Data("same data".utf8)
        let textItem = ClipboardItem(contentType: .text, rawData: data)
        let urlItem = ClipboardItem(contentType: .url, rawData: data)

        // Since hash is purely data-based, these should be equal
        XCTAssertEqual(textItem.dataHash, urlItem.dataHash,
                       "dataHash depends only on rawData, not contentType")
    }

    // MARK: - byteSize

    func testByteSizeMatchesRawDataCount() {
        let data = Data(repeating: 0xAB, count: 1024)
        let item = ClipboardItem(contentType: .image, rawData: data)

        XCTAssertEqual(item.byteSize, Int64(data.count))
        XCTAssertEqual(item.byteSize, 1024)
    }

    func testByteSizeForEmptyData() {
        let item = ClipboardItem(contentType: .text, rawData: Data())

        XCTAssertEqual(item.byteSize, 0)
    }

    func testByteSizeExplicitOverride() {
        let data = Data("short".utf8)
        let item = ClipboardItem(contentType: .text, rawData: data, byteSize: 5000)

        // Explicit byteSize should override the calculated value
        XCTAssertEqual(item.byteSize, 5000)
        XCTAssertNotEqual(item.byteSize, Int64(data.count))
    }

    // MARK: - SwiftData Persistence

    @MainActor
    func testPersistenceRoundTrip() throws {
        let container = try makeContainer()
        let context = ModelContext(container)

        let id = UUID()
        let rawData = Data("persisted text".utf8)
        let item = ClipboardItem(
            id: id,
            contentType: .richText,
            rawData: rawData,
            plainTextContent: "persisted text",
            sourceAppBundleID: "com.test.app",
            sourceAppName: "TestApp",
            capturedAt: Date(timeIntervalSince1970: 1_700_000_000)
        )

        context.insert(item)
        try context.save()

        // Fetch back from a fresh context on the same container
        let fetchContext = ModelContext(container)
        let descriptor = FetchDescriptor<ClipboardItem>()
        let fetched = try fetchContext.fetch(descriptor)

        XCTAssertEqual(fetched.count, 1)
        let fetchedItem = try XCTUnwrap(fetched.first)
        XCTAssertEqual(fetchedItem.id, id)
        XCTAssertEqual(fetchedItem.contentType, .richText)
        XCTAssertEqual(fetchedItem.rawData, rawData)
        XCTAssertEqual(fetchedItem.plainTextContent, "persisted text")
        XCTAssertEqual(fetchedItem.sourceAppBundleID, "com.test.app")
        XCTAssertEqual(fetchedItem.sourceAppName, "TestApp")
        XCTAssertEqual(fetchedItem.byteSize, Int64(rawData.count))
    }
}
